#!/usr/bin/env bash
# Removes PREROUTING rules no longer associated with running container for port forwarding
CONFIG=LOCATION
# Get global variables
if [[ -f "$CONFIG" ]]; then
  . "$CONFIG"
  . "$LIBISLET"
  readonly CONFIG LIBISLET USER INT BIND
else
  echo "$0: Warning: CONFIG not found"
  logger -p local0.notice -t "islet" "$0: $CONFIG not found!"
fi

IFS=$'\n'
for rule in $(iptables -t nat --list-rules PREROUTING | grep "${INT}.*${BIND}")
do
  id="$(echo "$rule" | awk -F : '{ print $2 }')"
  if ! ps -U "$USER" -o ppid,command --no-headers | awk '/docker/ { print $1 }' | grep -q "$id"
  then
    eval iptables -t nat "$(echo $rule | sed 's/^-./-D/')"
    log "Removing rule: iptables -t nat $(echo $rule | sed 's/^-./-D/')"
  fi
done
