#!/usr/bin/env bash
# Destroy containers which are older than x days (weeks, months, or years also if they were missed)
ARGC=$#
DAYS=3             # Overwritten by value in $CONFIG
CONFIG=/etc/sandbox/sandbox.conf
if [ -f $CONFIG ]; then
        source $CONFIG
else
        echo "$CONFIG not found! Exiting..."
        exit 1
fi

CONTAINERS=$(docker ps -a | \
 awk -v remove=$DAYS 'BEGIN { FS="[ ]{3,}" } \
        $4 ~ /[0-9]+ day|week|month|year/ && count=substr($4,1,2) \
                { 
                        if ( strtonum(count) > remove ) { 
                                printf("%s ", $1) 
                        }
                }')

if [ ! -z "$CONTAINERS" ]
then
        for ID in $CONTAINERS
        do
                #echo 'echo "Warning: Container lifetime limit reached. Destroying container..."' | docker attach $ID
                docker rm $ID
                logger -t "docker" "remove_old_containers.sh: Container $ID was older than $DAYS day. Stopped"
        done
fi
