#!/usr/bin/env bash
# Destroy containers which are older than x days (weeks, months, or years also if they were missed)
ARGC=$#
DAYS=3             # Overwritten by value in $CONFIG
CONFIG=LOCATION
if [ -f $CONFIG ]; then
        source $CONFIG
	source $LIBISLET
else
	echo "$0: Warning: CONFIG not found"
	logger -p local0.notice -t "islet" "$0: $CONFIG not found!"
fi

CONTAINERS=$(docker ps -a | \
 awk -v remove=$DAYS 'BEGIN { FS="[ ]{3,}" } \
        $4 ~ /[0-9]+ day|week|month|year/ && count=substr($4,1,2) \
                { 
                        if ( strtonum(count) > remove ) { 
                                printf("%s ", $1) 
                        }
                }')

if [ ! -z "$CONTAINERS" ]
then
        for ID in $CONTAINERS
        do
                #echo 'echo "Warning: Container lifetime limit reached. Destroying container..."' | docker attach $ID
                docker rm $ID
                logger -t "docker" "$0: Container $ID was older than $DAYS day. Stopped"
        done
fi
