#!/usr/bin/env bash
# Remove containers which are older than x DAYS, per-image config
ARGC="$#"
DAYS=3             # Overwritten by value in $CONFIG
CURRENT="$(date +"%s")"
METADATA="/var/lib/docker/containers/*/config.json"
CONFIG=LOCATION

# Get global variables
if [ -f "$CONFIG" ]; then
  . "$CONFIG"
  . "$LIBISLET"
  GLBDAYS="$DAYS"
  readonly CONFIG GLBDAYS
else
  echo "$0: Warning: CONFIG not found"
  logger -p local0.notice -t "islet" "$0: $CONFIG not found!"
fi

# Load variables from per-image configs
for config in $CONFIG_DIR/*.conf
do
  . "$config"
  for file in $METADATA
  do
    id="$(basename $(dirname $file))"
    if ! grep -q "$BASENAME" "$file"; then
      continue
    fi
    tstamp="$(egrep -o '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{9}Z' "$file" | head -n 1)"
    time="$(date --date=${tstamp} +"%s")"
    left="$((CURRENT-time))"
    delete="$((${DAYS:-GLBDAYS}*86400))"
    if [ "$left" -gt "$delete" ]; then
      logger -t "$0" "Container $id was older than $DAYS day. Stopped"
      docker rm "$id"
    fi
  done
  unset DAYS BASENAME
done
