#!/usr/bin/env bash
# Destroy users which are older than x days
CURRENT=$(date +"%s")
ARGC=$#
DAYS=3 		         # Overwritten by value in $CONFIG
DB=/var/tmp/zookeeper_db # Overwritten by value in $CONFIG
CONFIG=LOCATION
if [ -f $CONFIG ]; then
        source $CONFIG
else
	echo "$0: Warning: CONFIG not found"
fi

KEEP=$(($DAYS*86400))

while read line
do
        USER=$(echo "$line" | awk -F : '{ print $1 }')
        TIME=$(echo "$line" | awk -F : '{ print $3 }')
        ANSWER=$(echo $((CURRENT-TIME)))
        if [ $ANSWER -ge $KEEP ]
        then
                echo "Warning: User account $USER lifetime reached. Removing user..."
                logger -t "docker" "remove_old_users.sh: User account $USER was older than $DAYS day. Removed"
                sed -i "/^$USER:/d" $DB
        fi
done < $DB
