.Dd December 03, 2014
.Dt ISLET 5
.Os
.Sh NAME
.Nm Isolated, Scalable, and Lightweight Environment for Training
.Nd Configuration details
.Sh DESCRIPTION
An ISLET config file consists of shell variables that will be passed to either the docker
engine or to ISLET scripts to define the settings a training environment. An environment setting is of the form,
.Bd -literal
    NAME="value"
.Ed

There cannot be any whitespace between the variable name, the assignment operator, and the value.
Also, quoting is not required but recommended for security and whitespace issues.
ISLET has two types of configuration files that differ only with scope:
.Bd -literal -offset indent
Config        Description
------        --------------
Global        Global values inherited by all images but optionally superseded in Image configurations
Image         Per image configuration that are local to a specific image i.e. training environment
.Ed

The default locations for ISLET are
.Bd -literal -offset indent
Location                      Description
--------                      --------------
/etc/islet                    Configuration directory
/opt/islet                    Installation directory
/opt/islet/bin                ISLET scripts
/opt/islet/cron               Maintainance scripts
/opt/islet/lib                Library
.Ed

.Pa /etc/islet/islet.conf
is the global configuration file and must exist.
Settings in this file are sourced from all ISLET scripts. Image configuration files only pertain
to a specific Docker image and are sourced after the global file overriding any variables of the
same name giving granular control to your training environments. ``source'' can be used inside any
config file to include variables from other config files. These Image files are also to be placed in the
ISLET configuration directory. At the very least an Image configuration must contain the variable
IMAGE set to the name of docker image as matched in the output of ``docker images''.
Variables used to configure containers are passed directly to
.Xr docker-run 1
.Pp
.Sh EXAMPLE GLOBAL CONFIG FILE
.Bd -literal
#################################
# ISLET Main Configuration File #
#################################

# System Configuration
CONFIG_DIR="/etc/islet"                           # Directory to search for configuration files, used by scripts.
INSTALL_DIR="/opt/islet"                          # ISLET installation directory
LIBISLET="$INSTALL_DIR/lib/libislet"              # Common functions are stored in libislet
SHELL="$INSTALL_DIR/bin/islet_shell"              # ISLET shell, displays login banner, menu, and then launches islet_login
LAUNCH_CONTAINER="$INSTALL_DIR/bin/islet_login"   # User management script and container launcher
DB="/var/tmp/islet.db"                            # Credentials database. Must be readable by $USER
DOCKER_DIR="/var/lib/docker"                      # Location of Docker directory
STORAGE_BACKEND="devicemapper"                    # Docker storage backend, used to check if image exist
CONTAINER_PATH="$DOCKER_DIR/$STORAGE_BACKEND/mnt" # Path to container storage location, used by disk_limit
USER="demo"                                       # Linux system user created for ssh'ing to ISLET, give account to trainees
DEBUG="no"                                        # Enable debugging info to stdout and syslog

# Network Configuration
INTERFACE="eth0"        # Physical interface packets are arriving on
BIND="172.17.42.1"      # IP address to use to access services on containers (def: docker0)

# Security Configuration
VISIBLE="no"            # This config file is visible from config selection menu
ENABLE="no"             # Same as VISIBLE
FAILURE_COUNT=3         # Number of failed choice attempts before exiting (username, password, config)
DAYS=3                  # Container+user lifetime specified in days. Removed after # days by cron jobs
MAX_SIZE=1073741824     # Maximum size in bytes of container before it's purged by disk_limit
REMOVE="no"             # Container is removed after exit, user cannot re-attach and resume work
TIMEOUT="8h"            # Max runtime of containers, accepts timeout(1) arguments

source "$CONFIG_DIR"/security.conf  # Detailed kernel security capabilities to apply to containers

# Global Container Configuration
GLOBAL_OPTIONS=""            # Apply options to all configs, line should not be present in per image configs
export PLATFORM=islet"       # Exported to container's environment. Made available using ENVS in per image config
.Ed
.Sh EXAMPLE IMAGE CONFIG FILE
.Bd -literal
# Environment Configuration
IMAGE="broplatform/brolive"            # Launch containers from this Docker image, must match name in ``docker images''
DESCRIPTION="Bro 2.3.1 training image" # Brief description of image, listed in islet_shell selection menu
BASENAME="bro"                         # Container prefix as $BASENAME.$USERNAME (set in islet_login). Used for re-attachment.

# Security Configuration
VISIBLE="yes"                          # This config file is visible from config selection menu
DAYS=3                                 # Container lifetime specified in days, removed after x days by cron jobs

# Container Configuration
VIRTUSER="demo"                        # Account used when container is entered (Must exist in container!)
COMMAND="su $VIRTUSER"                 # Command to launch on container entry, typically used to get shell
CPUSHARE=1024                          # Proportion of cpu share allocation per container (Option used to be CPU)
MEMORY="256m"                          # Amount of memory allocated to each container (Option used to be RAM)
SWAP="100m"                            # Amount of swap memory allocated to each container
HOSTNAME="bro"                         # Set hostname in container. PS1 will end up as $VIRTUSER@$HOSTNAME:~$ in shell
NETWORK="none"                         # Disable networking by default: none; Enable networking: bridge
DNS="127.0.0.1"                        # Use loopback when networking is disabled to prevent error messages from resolver
MOUNT="-v /exercises:/exercises:ro"    # Mount point(s), sep. by -v: /src:/dst:attributes, ro = readonly (avoid rw)
CAP_NET_ADMIN="yes"                    # Configure the network
CAP_NET_RAW="yes"                      # Use RAW and PACKET sockets
LOCAL_OPTIONS=""                       # Apply any other options you want passed to docker run here
export IMAGE                           # Export variables for container environment
ENVS="PLATFORM IMAGE"                  # Make exported variables available in container

# Branding & Information
MOTD="Training materials are in /exercises" # Message of the day is displayed before entering container
BANNER="
================================
Welcome to the Bro configuration

    -----------
  /             \\
 |  (   (0)   )  |
 |            // |
  \\     <====// /
    -----------

A place to try out Bro.

================================
"
.Ed

.Sh SEE ALSO
.Xr docker-run 1 ,
.Sh AUTHORS
.An Jon Schipp jonschipp@gmail.com, http://jonschipp.com
.Sh BUGS
